---
- name: k8s prerquisites
  hosts: cluster 
  become: yes

  tasks: 
  - name: packages update
    zypper:
      name: '*' 
      state: latest
  - name: Check if a reboot is needed
    register: linux_reboot_required_file
    stat: path=/boot/do_purge_kernels get_md5=no

  - name: Reboot the SUSE/OpenSUSE box if kernel updated
    reboot:
      msg: "Reboot initiated by Ansible for kernel updates"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: linux_reboot_required_file.stat.exists
  
  - name: Install docker
    zypper:
      name: docker
      state: present
  
      #  - name: Start docker
      #systemd:
      #name: docker
      #state: restarted
      #enabled: yes

  - name: Create user rancher
    user:
      name: rancher
      append: yes
      groups: docker
  
  - name: Add public key to the Authorized keys
    authorized_key:
      user: rancher
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"


- name: k8s prerquisites
  hosts: loadbalancer
  become: yes


  tasks:
  - name: packages update
    zypper:
      name: '*'
      state: latest
  - name: Check if a reboot is needed
    register: linux_reboot_required_file
    stat: path=/boot/do_purge_kernels get_md5=no

  - name: Reboot the SUSE/OpenSUSE box if kernel updated
    reboot:
      msg: "Reboot initiated by Ansible for kernel updates"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: linux_reboot_required_file.stat.exists

  - name: Install nginx
    zypper: 
      name: nginx
      state: present

  - name: Config nginx
    template:
      src: ./nginx.j2
      dest: /etc/nginx/nginx.conf 
      owner: root
      group: root
      mode: '0644'




